### ISSUE TITLE
zfs.py has windows line endings

### ISSUE THREAD

**Issue by Whytey** [blind-oracle/zabbix-zfs#1]
Just installed this.  It is working well but I needed to tweak the zfs.py script to make it work.

I downloaded the script from github using wget, which pulled the file as is.  When Zabbix tried to do discovery, it threw an error that indicated we had a windows style line ending (carriage return + new line):

```usr/bin/env: ‘python3\r’: No such file or directory```

I fixed this by running the following Perl script...

```perl -pe 's/\r$//g' zfs-storage-discovery.py zfs-storage-discovery.py.new```

...then copying the new file over the original.  Everything went swimmingly then.

Cheers!

**Comment by blind-oracle** [comment]
Strange, considering that I developed it on Mac if I remember... fixed, thanks!
