### ISSUE TITLE
Won't import into Zabbix 7.0.0alpha1

### ISSUE THREAD

**Issue by elyograg** [blind-oracle/zabbix-zfs#15]
Trying to import into 7.0.0alpha1 throws an error.
`Incorrect trigger expression. Host "Template_ZFS" does not exist or you have no access to this host.`

**Comment by elyograg** [comment]
I had this working on 6.x versions.

**Comment by blind-oracle** [comment]
Well, I don't have 7.0 since it's alpha so can't help. If you want you can try adapting the template to make it work and do a PR. Otherwise once 7.0 is released I might try to do it.

**Comment by elyograg** [comment]
I had rebuilt my zabbix server, but saved the database dump from the time when I upgraded from 6.4.2 to 7.0.0alpha1.  I was able to get a second server started with that database.  I exported the template from that, and here is a version of the template that works with 7.0.

[zfs_template_7.0.zip](https://github.com/blind-oracle/zabbix-zfs/files/11702128/zfs_template_7.0.zip)

**Comment by blind-oracle** [comment]
Can you do a PR to add this file as some `template_zfs_zbx7.xml` or smth like it for others to use?

**Comment by elyograg** [comment]
PR created and linked to this issue.  It's not in XML format, I just chose the first option when exporting it.

**Comment by blind-oracle** [comment]
Thanks, merged. Good, XML should go away I guess :)
