### ISSUE TITLE
Getting an error while running zfs.py

### ISSUE THREAD

**Issue by veesiom** [blind-oracle/zabbix-zfs#19]
Hi there!

I'm getting this error when i'm trying to run ./zfs.py locally and i don't really know what's causing it:
```
Traceback (most recent call last):
  File "/etc/zabbix/scripts/./zfs.py", line 194, in <module>
    'arc': arc_stats(),
           ^^^^^^^^^^^
  File "/etc/zabbix/scripts/./zfs.py", line 173, in arc_stats
    'meta_limit': r['arc_meta_limit'],
                  ~^^^^^^^^^^^^^^^^^^
KeyError: 'arc_meta_limit'
``` 
As soon as i am commenting out this line it's getting to work:
```
'arc': arc_stats(),
``` 

If there's any additional info i could provide, i'll be happy to do so once you ask.

**Comment by blind-oracle** [comment]
Which version of ZFS you're running?

**Comment by veesiom** [comment]
```
root@pve01:~# modinfo zfs | grep version 
version:        2.2.2-pve1
srcversion:     64DFECF22645F1BD34FFBB0
vermagic:       6.5.11-8-pve SMP preempt mod_unload modversions 
```

**Comment by blind-oracle** [comment]
Thanks, sorry for long wait, I didn't have much time to take care about this repo. I've removed the `arc_meta_limit` from there so that it work.

I hope when OpenZFS 2.3 comes out I'll rewrite this to use the new JSON export that it will have.
