### ISSUE TITLE
Degraded means Offline - point of view

### ISSUE THREAD

**Issue by lonnie44** [blind-oracle/zabbix-zfs#3]
Hi,

Thanks a lot for this, I have just a friendly note:

I got a degraded pool which trigger Zabbix to raise disaster issue and says the pool is offline.
In the script I found it, " if not equal online => offline ".

For me degraded is not offline, especially for raidZ2/3 or mirrors with more than 2 disks.
And also if it is really disastrous depends on the setup and I like to keep the highest trigger state free for worse scenarios, like real offline or if it is really critical like 2 disks are faulted in a raidZ2 where I might consider limiting access or something.

But I guess this is a point of view question, so I'm totally fine if stays that way.
I just wanted to mention it to be sure you considered it.

Cheers!

**Comment by blind-oracle** [comment]
Yes, I agree that's not correct. Will try to fix when I have time, PRs welcome :)

**Comment by maufimauf** [comment]
@lonnie44 
I guess this will solve your problem as well => #13

**Comment by lonnie44** [comment]
@maufimauf many thanks, works great.

--
Testet on:
Zabbix 5.4
ZoL 0.8.3
