### ISSUE TITLE
Py Script errors

### ISSUE THREAD

**Issue by bmacao** [blind-oracle/zabbix-zfs#4]
Hi, i have detected a few errors when deploying monit to Zabbix ( 4.4.4 ).

1.  Template xml file needed line change 3 to:
<version>4.4</version>

2. Script pops errors:
 Traceback (most recent call last):
  File "./zfs.py", line 167, in <module>
    scrub, vdev_errors = pool_status()
  File "./zfs.py", line 70, in pool_status
    ], split=r'\s+')
  File "./zfs.py", line 17, in run
    stderr=DEVNULL
  File "/usr/lib/python3.6/subprocess.py", line 356, in check_output
    **kwargs).stdout
  File "/usr/lib/python3.6/subprocess.py", line 438, in run
    output=stdout, stderr=stderr)
subprocess.CalledProcessError: Command '['/sbin/zpool', 'status', '-Pp']' returned non-zero exit status 2.

**FIX: Line 69 change from '-Pp' to '-P'**

Traceback (most recent call last):
  File "./zfs.py", line 170, in <module>
    'vdevs': vdev_list(vdev_errors),
  File "./zfs.py", line 115, in vdev_list
    } for x in r if x[0].startswith('/')}
  File "./zfs.py", line 115, in <dictcomp>
    } for x in r if x[0].startswith('/')}
IndexError: list index out of range

**FIX: Line 115 change from } for x in r if x[0].startswith('/')} to } for x in r if x[1].startswith('/')}**

Good Job anyway.
Best Regards

**Comment by blind-oracle** [comment]
Which ZFS version are you using? This code is meant for OpenZFS 2.x

**Comment by bmacao** [comment]
Hi, here are the modules at server:
modinfo zfs
filename:       /lib/modules/4.15.0-158-generic/kernel/zfs/zfs.ko
version:        0.7.5-1ubuntu16.12
license:        CDDL
author:         OpenZFS on Linux
description:    ZFS

**Comment by blind-oracle** [comment]
@bmacao yep, those are very old, it's better to upgrade to at least 0.8.x or better 2.x
